version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    hostname: "some-rabbit"

  website:
    build:
      context: ./personal_flask_website/
      dockerfile: Dockerfile
    expose:
      - 8000
    command: >
      gunicorn -b 0.0.0.0:8000
      --reload
      --timeout 90
      --graceful-timeout 80
      app:create_app()
    ports:
      - 8000:8000
    links:
      - yt2spec
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=0

  yt2spec:
    build:
      context: ./advert_detection/advert_detection/
      dockerfile: Dockerfile
    expose:
      - 6060
    command: >
      python3 -u ./flask_rest.py
    ports:
      - 6060:6060

  sleeper:
    build:
      context: ./sleeper/sleeper/
      dockerfile: Dockerfile
    expose:
      - 1234
    command: >
      python3 -u ./flask_rest.py
    ports:
      - 1234:1234
