version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    #ports:
    #  - 5672:5672
    #  - 15672:15672
    hostname: "some-rabbit"

  website:
    build:
      context: ./personal_flask_website/
      dockerfile: Dockerfile
    expose:
      - 8000
    command: >
      gunicorn -b 0.0.0.0:8000
      --reload
      --timeout 90
      --graceful-timeout 80
      app:myapp
    ports:
      - 8000:8000
    links:
      - yt2spec
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=0

  celery:
    build:
      context: ./personal_flask_website/
      dockerfile: Dockerfile
    command: celery worker --loglevel=info -A blueprints.celery_tester.tasks
    links:
      - rabbitmq

  celeryflower:
    build:
      context: ./personal_flask_website/
      dockerfile: Dockerfile
    command: celery -A blueprints.celery_tester.tasks flower
    ports:
      - 5555:5555
    links:
      - rabbitmq

  yt2spec:
    build:
      context: ./advert_detection/advert_detection/
      dockerfile: Dockerfile
    expose:
      - 6060
    command: >
      python3 -u ./flask_rest.py
    ports:
      - 6060:6060

  sleeper:
    build:
      context: ./sleeper/sleeper/
      dockerfile: Dockerfile
    expose:
      - 1234
    command: >
      python3 -u ./flask_rest.py
    ports:
      - 1234:1234

  shortstraw:
    build:
      context: ./short_straw/short_straw/
      dockerfile: Dockerfile
    expose:
      - 2828
    command: >
      python3 -u ./flask_rest.py
    ports:
      - 2828:2828
    depends_on:
      - "postgres"

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: shortstraw
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
    - ./postgres_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    links:
    - postgres
    depends_on:
    - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
    - "5050:80"
