version: '3'

services:
  website:
    build:
      context: ./personal_flask_website
      dockerfile: Dockerfile
    command: >
      gunicorn -b 0.0.0.0:8000 
      --reload
      personal_flask_website.app
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
