version: '3'

services:
  website:
    build:
      context: ./personal_flask_website/
      dockerfile: Dockerfile
    expose:
      - 8000
    command: >
      gunicorn -b 0.0.0.0:8000
      --reload
      --timeout 90
      --graceful-timeout 80
      app:create_app()
    ports:
      - 8000:8000
    links:
      - yt2spec
    environment:
      - PYTHONUNBUFFERED=0

  yt2spec:
    build:
      context: ./advert_detection/advert_detection/
      dockerfile: Dockerfile
    expose:
      - 6060
    command: >
      python3 ./flask_rest.py
    ports:
      - 6060:6060
